### ISSUE TITLE
v5.4.0 "Cannot find module '@sindresorhus/is' or its corresponding type declarations"

### ISSUE THREAD

**Issue by Kamahl19** [sindresorhus/is#179]
After upgrading to 5.4.0 I am getting "Cannot find module '@sindresorhus/is' or its corresponding type declarations"

**Comment by tomasz-zablocki-ziegert** [comment]
The same issue here, didn't happen on 5.3.0

**Comment by sindresorhus** [comment]
The problem is your TypeScript config. Make sure you'are on TS 5 or later and use this config: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm

**Comment by tomasz-zablocki-ziegert** [comment]
Thank you very much
